export default defineEventHandler((event) => {
  return {
    category: [
      'beauty',
      'fragrances',
      'furniture',
      'groceries',
      'home-decoration',
      'kitchen-accessories',
      'laptops',
      'mens-shirts',
      'mens-shoes',
      'mens-watches',
      'mobile-accessories',
      'motorcycle',
      'skin-care',
      'smartphones',
      'sports-accessories',
      'sunglasses',
      'tablets',
      'tops',
      'vehicle',
      'womens-bags',
      'womens-dresses',
      'womens-jewellery',
      'womens-shoes',
      'womens-watches'
    ],
    brand: [
      'Essence',
      'Glamour Beauty',
      'Velvet Touch',
      'Chic Cosmetics',
      'Nail Couture',
      'Calvin Klein',
      'Chanel',
      'Dior',
      'Dolce & Gabbana',
      'Gucci',
      'Annibale Colombo',
      'Furniture Co.',
      'Knoll',
      'Bath Trends',
      'Apple',
      'Asus',
      'Huawei',
      'Lenovo',
      'Dell',
      'Fashion Trends',
      'Gigabyte',
      'Classic Wear',
      'Casual Comfort',
      'Urban Chic',
      'Nike',
      'Puma',
      'Off White',
      'Fashion Timepieces',
      'Longines',
      'Rolex',
      'Amazon',
      'Beats',
      'TechGear',
      'GadgetMaster',
      'SnapTech',
      'ProVision',
      'Generic Motors',
      'Kawasaki',
      'MotoGP',
      'ScootMaster',
      'SpeedMaster',
      'Attitude',
      'Olay',
      'Vaseline',
      'Oppo',
      'Realme',
      'Samsung',
      'Vivo',
      'Fashion Shades',
      'Fashion Fun',
      'Chrysler',
      'Dodge',
      'Fashionista',
      'Heshe',
      'Prada',
      'Elegance Collection',
      'Comfort Trends',
      'Calvin Klein',
      'Fashion Diva',
      'Pampi',
      'Fashion Express',
      'IWC',
      'Fashion Gold',
      'Fashion Co.'
    ],
    tags: [
      'beauty',
      'mascara',
      'eyeshadow',
      'face powder',
      'lipstick',
      'nail polish',
      'fragrances',
      'perfumes',
      'furniture',
      'beds',
      'sofas',
      'bedside tables',
      'office chairs',
      'bathroom',
      'groceries',
      'fruits',
      'meat',
      'pet supplies',
      'cat food',
      'dog food',
      'dairy',
      'seafood',
      'vegetables',
      'condiments',
      'desserts',
      'beverages',
      'coffee',
      'grains',
      'health supplements',
      'household essentials',
      'home decor',
      'swing',
      'photo frame',
      'artificial plants',
      'plant accessories',
      'lighting',
      'kitchen tools',
      'utensils',
      'drinkware',
      'cups',
      'kitchen appliances',
      'blenders',
      'cookware',
      'woks',
      'cutting boards',
      'juicers',
      'slicers',
      'cooktops',
      'strainers',
      'cutlery',
      'storage',
      'microwaves',
      'organization',
      'pans',
      'dinnerware',
      'plates',
      'tongs',
      'pots',
      'turners',
      'baking',
      'ice cube trays',
      'peelers',
      'laptops',
      'apple',
      'clothing',
      "men's shirts",
      "men's t-shirts",
      'footwear',
      'athletic shoes',
      'sports cleats',
      'casual shoes',
      'watches',
      'leather watches',
      'luxury watches',
      "women's shoes",
      'slippers',
      'heel shoes',
      'electronics',
      'smart speakers',
      'wireless earphones',
      'over-ear headphones',
      'wireless chargers',
      'smartwatches',
      'phone accessories',
      'camera accessories',
      'selfie accessories',
      'motorcycles',
      'sportbikes',
      'scooters',
      'personal care',
      'hand soap',
      'body wash',
      'body lotion',
      'smartphones',
      'apple',
      'oppo',
      'realme',
      'samsung galaxy',
      'vivo',
      'sports equipment',
      'american football',
      'baseball',
      'basketball',
      'cricket',
      'badminton',
      'football',
      'golf',
      'tennis',
      'volleyball',
      'eyewear',
      'sunglasses',
      'party glasses'
    ],
    availabilityStatus: ['In Stock', 'Low Stock', 'Out of Stock'],
    shippingInformation: [
      'Ships overnight',
      'Ships in 1-2 business days',
      'Ships in 1 week',
      'Ships in 2 weeks',
      'Ships in 1 month',
      'Ships in 3-5 business days'
    ],
    returnPolicy: [
      'No return policy',
      '7 days return policy',
      '30 days return policy',
      '60 days return policy',
      '90 days return policy'
    ],
    warrantyInformation: [
      'No warranty',
      '1 week warranty',
      '1 month warranty',
      '3 months warranty',
      '6 months warranty',
      '1 year warranty',
      '2 year warranty',
      '3 year warranty',
      '5 year warranty',
      'Lifetime warranty'
    ]
  }
})
